# Computational Intelligence Lab Report - Lab 1 - Prof. Amini
## Seyed Mohammadsaleh Mirzatabatabaei - 9623105 


---
## Pre-Report
---


> **1- Python Applications:**
*   Web Development
*   List item
*   Game Development
*   Machine Learning and Artificial Intelligence
*   Data Science and Data Visualization
*   Desktop GUI
*   Web Scraping Applications
*   Business Applications
*   Audio and Video Applications
*   CAD Applications
*   Embedded Applications

> **2- Difference between MATLAB and Python:**
The biggest technical difference between MATLAB and Python is that in MATLAB, everything is treated as an array, while in Python everything is a more general object. For instance, in MATLAB, strings are arrays of characters or arrays of strings, while in Python, strings have their own type of object called str .


> **3- advantages of Python over Matlab Python:** data structures are superior to Matlab data structures. Python provides more control over the organization of one's code and better namespace management. Python makes it easy to maintain multiple versions of shared libraries. Python offers more choice in graphics packages and toolsets





---
## Report
---


First, we import the packages we need in Python, we then define sigmoid functions and its derivative. 

These two functions use the predefined functions of the Numpy to execute on the each member of matrix.

In [1]:
from math import exp, sin, pi
import numpy as np


def sigmoid(mat):
  return (2 / (1 + np.exp(-mat))) - 1

def dsigmoid(mat):
  return (1 - sigmoid(mat) ** 2) / 2

In this step, the sigmatrix function mentioned in the work report is defined in two ways:

1.   Using sum method in Numpy package which is very simple.

2.   Using two for loops used to the sum elements of the matrix.

In the second method, if the matrix dimension increases, the number of loops should increase by the same number, which is impossible in high dimensions, so the first method is suggested.

In [2]:
# sigmatrix calculated by np functions
def sigmatrix(mat):
  return np.sum(sigmoid(mat)), np.sum(dsigmoid(mat))

# sigmatrix simply with for loops and summation
def sigmatrix2(mat, n, m):
  sigmat = 0
  dsigmat = 0
  for i in range(n):
    for j in range(m):
      sigmat = sigmat + sigmoid(mat[i, j])
      dsigmat = dsigmat + dsigmoid(mat[i, j])
  return sigmat, dsigmat

Finally, to test the functions, the matrix M is defined according to the work report, and the functions are executed on this matrix and the outputs are displayed:



In [3]:
M = np.array([[1, 0, sin(pi/4)], [0, 1, sin(pi/2)], [1, 0, 1]])
print(f"Matrix M :\n {M} \n")
print(f"Sigmoid of Matrix M:\n {sigmoid(M)} \n")
print(f"Dsigmoid of Matrix M:\n {dsigmoid(M)} \n")
print(f"Sigmatrix outputs of Matrix M (method I):\n {sigmatrix(M)} \n")
print(f"Sigmatrix outputs of Matrix M (method II):\n {sigmatrix2(M, 3, 3)}")

Matrix M :
 [[1.         0.         0.70710678]
 [0.         1.         1.        ]
 [1.         0.         1.        ]] 

Sigmoid of Matrix M:
 [[0.46211716 0.         0.3395231 ]
 [0.         0.46211716 0.46211716]
 [0.46211716 0.         0.46211716]] 

Dsigmoid of Matrix M:
 [[0.39322387 0.5        0.44236203]
 [0.5        0.39322387 0.39322387]
 [0.39322387 0.5        0.39322387]] 

Sigmatrix outputs of Matrix M (method I):
 (2.6501088849533625, 3.908481365155245) 

Sigmatrix outputs of Matrix M (method II):
 (2.6501088849533625, 3.908481365155244)



## Exercise
---


The exercise is performed like the report and two functions are defined:

In the first function, predefined Numpy package methods are used and in the second method, the troublesome method of using iterative loops.

To Test the functions we define random matrix M (3*3) and display the output.

In [4]:
from math import exp
import numpy as np


# tanhmatrix calculated by np functions
def tanhmatrix(mat):
  return np.sum(np.tanh(mat))

# tanhmatrix simply with for loops and summation
def tanhmatrix2(mat, n, m):
  tanhmat = 0
  for i in range(n):
    for j in range(m):
      tanhmat = tanhmat + (exp(mat[i, j]) - exp(-mat[i, j])) / (exp(mat[i, j]) + exp(-mat[i, j]))
  return tanhmat
  

M = np.random.randn(3, 3)
print(f"Matrix M :\n {M} \n")
print(f"Tanhmatrix outputs of Matrix M (method I):\n {tanhmatrix(M)} \n")
print(f"Tanhatrix outputs of Matrix M (method II):\n {tanhmatrix2(M, 3, 3)}")

Matrix M :
 [[-1.20754525 -1.56804464 -0.15136428]
 [-0.24980713  0.33077312 -0.02601507]
 [-1.19980095 -0.02119167 -0.14695743]] 

Tanhmatrix outputs of Matrix M (method I):
 -2.8550968150001332 

Tanhatrix outputs of Matrix M (method II):
 -2.8550968150001337
